#!/usr/bin/env python3
"""Generate the aggregated portfolio inventory under ``docs/<lang>/portfolio/``.

Reads the committed snapshot ``portfolio/aggregate.yml`` (populated by the
``portfolio-audit`` skill's Render operation) and renders one section per
Portfolio-Member repository plus a capability-to-repository Mermaid map and a
historical-capabilities appendix, per
``spec/portfolio/portfolio-management/`` §Documentation rendering.

Determinism is load-bearing: the output is a pure function of
``portfolio/aggregate.yml`` and the configured languages, with no timestamps or
ordering nondeterminism, so the committed pages can be verified fresh in CI via
``git diff --exit-code`` (mirroring the skill-agent catalog mechanism). Edit the
snapshot, never the generated pages.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
AGGREGATE = REPO_ROOT / "portfolio" / "aggregate.yml"
SPEC_CONFIG = REPO_ROOT / "spec" / ".spec-config.yml"

TRACK = "developer-docs"
AUDIENCE = "maintainer"
CONTENT_MODE = "reference"

STATUS_BADGE = {
    "active": "✅ active",
    "experimental": "🧪 experimental",
    "deprecated": "⚠️ deprecated",
    "planned": "🗓️ planned",
}

# Per-language page chrome. The snapshot data (capability descriptions, mission
# statements) is English source-of-truth and is rendered verbatim in both trees;
# only the structural labels below are translated.
L = {
    "en": {
        "title": "Portfolio inventory",
        "h1": "Portfolio inventory",
        "intro": (
            "Aggregated capability inventory across the active `nolte/*` portfolio, "
            "generated from each member repository's `project/portfolio.yml` manifest. "
            "This page is auto-generated — edit `portfolio/aggregate.yml` (or re-run the "
            "`portfolio-audit` skill's Render operation), not this file."
        ),
        "map": "Capability map",
        "map_intro": "Capability-to-repository mapping across the portfolio.",
        "mission": "Mission",
        "capabilities": "Capabilities",
        "col_cap": "Capability",
        "col_status": "Status",
        "col_desc": "Description",
        "col_aud": "Audiences",
        "peers": "Peer references",
        "peers_none": "_None declared._",
        "historical": "Historical capabilities",
        "historical_none": "_No archived repositories with registered capabilities._",
        "archived_on": "archived",
    },
    "de": {
        "title": "Portfolio-Inventar",
        "h1": "Portfolio-Inventar",
        "intro": (
            "Aggregiertes Fähigkeiten-Inventar über das aktive `nolte/*`-Portfolio, "
            "generiert aus dem `project/portfolio.yml`-Manifest jedes Member-Repositories. "
            "Diese Seite ist auto-generiert — bearbeite `portfolio/aggregate.yml` (oder lass "
            "die Render-Operation des `portfolio-audit`-Skills erneut laufen), nicht diese Datei."
        ),
        "map": "Fähigkeiten-Karte",
        "map_intro": "Fähigkeit-zu-Repository-Zuordnung über das Portfolio.",
        "mission": "Mission",
        "capabilities": "Fähigkeiten",
        "col_cap": "Fähigkeit",
        "col_status": "Status",
        "col_desc": "Beschreibung",
        "col_aud": "Zielgruppen",
        "peers": "Peer-Referenzen",
        "peers_none": "_Keine deklariert._",
        "historical": "Historische Fähigkeiten",
        "historical_none": "_Keine archivierten Repositories mit registrierten Fähigkeiten._",
        "archived_on": "archiviert",
    },
}

AUTOGEN = (
    "<!-- AUTO-GENERATED by scripts/docs/gen_portfolio.py from "
    "portfolio/aggregate.yml. Do not edit by hand; edit the snapshot and run "
    "`task docs:portfolio`. -->"
)


class PortfolioError(Exception):
    """Raised on malformed snapshot input."""


def load_languages() -> list[str]:
    cfg = yaml.safe_load(SPEC_CONFIG.read_text(encoding="utf-8")) or {}
    langs = cfg.get("languages") or ["en"]
    if not isinstance(langs, list) or not langs:
        raise PortfolioError("spec/.spec-config.yml: 'languages' must be a non-empty list")
    return [str(x) for x in langs]


def _node_id(prefix: str, n: int) -> str:
    return f"{prefix}{n}"


def _esc(text: str) -> str:
    """Escape a Mermaid node label (quotes only; labels are wrapped in quotes)."""
    return str(text).replace('"', "'")


def render_mermaid(members: list[dict]) -> list[str]:
    # Per spec/project/mermaid-diagrams/ every Mermaid block under docs/<lang>/
    # MUST be preceded by a diagram-source comment; this block is derived from
    # the committed snapshot, so docs-freshness can detect drift against it.
    out = [
        "<!-- diagram-source: derived—portfolio/aggregate.yml -->",
        "```mermaid",
        "flowchart LR",
    ]
    for ri, m in enumerate(members):
        rid = _node_id("R", ri)
        out.append(f'    {rid}["{_esc(m["repo"])}"]')
        for ci, cap in enumerate(m.get("capabilities", [])):
            cid = _node_id(f"R{ri}C", ci)
            out.append(f'    {cid}["{_esc(cap["name"])}"]')
            out.append(f"    {rid} --> {cid}")
    # Outbound peer edges (repo-to-repo) when declared.
    repo_to_rid = {m["repo"]: _node_id("R", ri) for ri, m in enumerate(members)}
    for ri, m in enumerate(members):
        for peer in m.get("peers") or []:
            target = repo_to_rid.get(peer)
            if target:
                out.append(f'    R{ri} -.peer.-> {target}')
    out.append("```")
    return out


def render_member(m: dict, t: dict) -> list[str]:
    out = [f"## {m['repo']}", ""]
    mission = (m.get("mission_statement") or "").strip()
    if mission:
        out += [f"> {mission}", ""]
    out += [f"### {t['capabilities']}", ""]
    caps = m.get("capabilities", [])
    if caps:
        out += [
            f"| {t['col_cap']} | {t['col_status']} | {t['col_desc']} | {t['col_aud']} |",
            "|---|---|---|---|",
        ]
        for cap in caps:
            badge = STATUS_BADGE.get(str(cap.get("status", "")), str(cap.get("status", "—")))
            desc = " ".join(str(cap.get("description", "")).split())
            aud = "; ".join(cap.get("audience") or []) or "—"
            name = cap.get("name", "—")
            out.append(f"| `{name}` | {badge} | {desc} | {aud} |")
        out.append("")
    peers = m.get("peers") or []
    out += [f"### {t['peers']}", ""]
    if peers:
        out += [f"- `{p}`" for p in peers] + [""]
    else:
        out += [t["peers_none"], ""]
    return out


def render_page(lang: str, snapshot: dict) -> str:
    t = L.get(lang, L["en"])
    members = sorted(snapshot.get("members", []), key=lambda m: m["repo"])
    historical = snapshot.get("historical") or []

    fm = [
        "---",
        f"title: {t['title']}",
        f"audience: [{AUDIENCE}]",
        f"content_mode: {CONTENT_MODE}",
        f"track: {TRACK}",
        "last_updated: generated",
        "---",
        "",
    ]
    body = [AUTOGEN, "", f"# {t['h1']}", "", t["intro"], ""]
    body += [f"## {t['map']}", "", t["map_intro"], ""]
    body += render_mermaid(members)
    body += [""]
    for m in members:
        body += render_member(m, t)
    body += [f"## {t['historical']}", ""]
    if historical:
        for h in historical:
            cap = h.get("name", "—")
            repo = h.get("repo", "—")
            date = h.get("archived", "—")
            body.append(f"- `{cap}` ({repo}) — {t['archived_on']} {date}")
        body.append("")
    else:
        body += [t["historical_none"], ""]
    return "\n".join(fm + body).rstrip() + "\n"


def main() -> int:
    if not AGGREGATE.exists():
        raise PortfolioError(f"missing snapshot: {AGGREGATE}")
    snapshot = yaml.safe_load(AGGREGATE.read_text(encoding="utf-8")) or {}
    if not isinstance(snapshot.get("members"), list):
        raise PortfolioError("portfolio/aggregate.yml: top-level 'members' must be a list")
    for lang in load_languages():
        out_dir = REPO_ROOT / "docs" / lang / "portfolio"
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.md").write_text(render_page(lang, snapshot), encoding="utf-8")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except PortfolioError as exc:
        print(f"gen_portfolio: {exc}", file=sys.stderr)
        sys.exit(1)
